export const ADMIN_COLLAPSE_CHANGE = 'ADMIN_COLLAPSE_CHANGE';
export const ADMIN_GET_AGENT_LIST_BEGIN = 'ADMIN_GET_AGENT_LIST_BEGIN';
export const ADMIN_GET_AGENT_LIST_SUCCESS = 'ADMIN_GET_AGENT_LIST_SUCCESS';
export const ADMIN_GET_AGENT_LIST_FAILURE = 'ADMIN_GET_AGENT_LIST_FAILURE';
export const ADMIN_GET_AGENT_LIST_DISMISS_ERROR = 'ADMIN_GET_AGENT_LIST_DISMISS_ERROR';
